nohup: 입력 무시
Watching for file changes with StatReloader
Not Found: /
[08/May/2023 15:05:03] "GET / HTTP/1.1" 404 2280
Not Found: /favicon.ico
[08/May/2023 15:05:05] "GET /favicon.ico HTTP/1.1" 404 2331
[08/May/2023 15:05:08] "GET /pybo HTTP/1.1" 301 0
[08/May/2023 15:05:09] "GET /pybo/ HTTP/1.1" 200 7849
[08/May/2023 15:05:10] "GET /static/bootstrap.min.js HTTP/1.1" 200 59219
[08/May/2023 15:05:11] "GET /static/bootstrap.min.css HTTP/1.1" 200 163873
[08/May/2023 15:05:11] "GET /static/style.css HTTP/1.1" 200 0
[08/May/2023 15:05:13] "GET /common/login/ HTTP/1.1" 200 2245
[08/May/2023 15:05:33] "GET /common/login/ HTTP/1.1" 200 2245
[08/May/2023 15:05:40] "GET /common/login/ HTTP/1.1" 200 2245
[08/May/2023 15:05:53] "GET /admin HTTP/1.1" 301 0
[08/May/2023 15:05:53] "GET /admin/ HTTP/1.1" 302 0
[08/May/2023 15:05:54] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2235
[08/May/2023 15:05:54] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[08/May/2023 15:05:54] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2616
[08/May/2023 15:05:54] "GET /static/admin/css/login.css HTTP/1.1" 200 954
[08/May/2023 15:05:54] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18575
[08/May/2023 15:05:54] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3401
[08/May/2023 15:05:54] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[08/May/2023 15:05:55] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[08/May/2023 15:05:55] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[08/May/2023 15:06:01] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[08/May/2023 15:06:01] "GET /admin/ HTTP/1.1" 200 7157
[08/May/2023 15:06:01] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[08/May/2023 15:06:01] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[08/May/2023 15:06:01] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[08/May/2023 15:06:01] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[08/May/2023 15:06:01] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[08/May/2023 15:06:06] "GET /common/login/ HTTP/1.1" 200 2245
[08/May/2023 15:06:22] "GET /common/login/ HTTP/1.1" 200 2245
[08/May/2023 15:07:57] "GET /common/login/ HTTP/1.1" 200 2236
[08/May/2023 15:08:02] "POST /common/login/ HTTP/1.1" 302 0
Not Found: /accounts/profile/
[08/May/2023 15:08:03] "GET /accounts/profile/ HTTP/1.1" 404 2349
/workspace/py_django/projects/mysite/config/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 15:04:55
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/config/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 15:08:53
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 15:09:37] "GET /common/login/ HTTP/1.1" 200 2236
[08/May/2023 15:09:41] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 15:09:41] "GET / HTTP/1.1" 200 7849
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/py_django/projects/mysite/pybo/views.py", line 15, in index
    return render(request, 'pybo/question_list.html', context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
[08/May/2023 15:11:38] "GET / HTTP/1.1" 500 180498
/workspace/py_django/projects/mysite/common/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 15:09:35
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 15:12:42] "GET / HTTP/1.1" 200 7874
[08/May/2023 15:12:44] "GET /pybo/ HTTP/1.1" 200 7874
[08/May/2023 15:12:46] "GET /pybo/202/ HTTP/1.1" 200 2737
[08/May/2023 15:12:48] "GET /pybo/ HTTP/1.1" 200 7874
[08/May/2023 15:12:56] "GET /common/logout/ HTTP/1.1" 200 1368
[08/May/2023 15:12:59] "GET /admin/ HTTP/1.1" 302 0
[08/May/2023 15:12:59] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2235
[08/May/2023 15:13:02] "GET /common/logout/ HTTP/1.1" 200 1368
[08/May/2023 15:13:04] "GET /admin/ HTTP/1.1" 302 0
[08/May/2023 15:13:05] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2235
/workspace/py_django/projects/mysite/config/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 15:12:40
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 15:13:37] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2235
[08/May/2023 15:13:43] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[08/May/2023 15:13:43] "GET /admin/ HTTP/1.1" 200 7157
[08/May/2023 15:13:47] "GET /pybo/ HTTP/1.1" 200 7874
[08/May/2023 15:13:49] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 15:13:49] "GET / HTTP/1.1" 200 7861
[08/May/2023 15:13:53] "GET /common/login/ HTTP/1.1" 200 2248
[08/May/2023 15:13:59] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 15:13:59] "GET / HTTP/1.1" 200 7874
[08/May/2023 15:27:20] "GET /pybo/ HTTP/1.1" 200 7899
[08/May/2023 15:27:21] "GET /common/logout/ HTTP/1.1" 302 0
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/py_django/projects/mysite/pybo/views.py", line 15, in index
    return render(request, 'pybo/question_list.html', context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'signup' not found. 'signup' is not a valid view function or pattern name.
[08/May/2023 15:27:21] "GET / HTTP/1.1" 500 179531
/workspace/py_django/projects/mysite/common/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 15:13:30
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/config/urls.py", line 23, in <module>
    path('common/', include('common.urls')),
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/common/urls.py", line 10, in <module>
    path('signup/', views.signup, name='signup'),
AttributeError: module 'common.views' has no attribute 'signup'
/workspace/py_django/projects/mysite/common/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
