nohup: 입력 무시
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:27:13
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 16:29:37] "GET / HTTP/1.1" 200 7899
[08/May/2023 16:29:39] "GET /pybo/202/ HTTP/1.1" 200 2762
[08/May/2023 16:29:47] "GET /admin/ HTTP/1.1" 200 7157
[08/May/2023 16:29:49] "GET /admin/pybo/answer/ HTTP/1.1" 200 7046
[08/May/2023 16:29:49] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[08/May/2023 16:29:51] "GET /admin/pybo/answer/3/change/ HTTP/1.1" 200 22852
[08/May/2023 16:29:51] "GET /static/admin/css/forms.css HTTP/1.1" 200 8878
[08/May/2023 16:29:51] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[08/May/2023 16:29:51] "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[08/May/2023 16:29:51] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[08/May/2023 16:29:51] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
[08/May/2023 16:29:51] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[08/May/2023 16:29:51] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[08/May/2023 16:29:52] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[08/May/2023 16:29:52] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[08/May/2023 16:29:55] "GET /admin/pybo/answer/ HTTP/1.1" 200 7046
[08/May/2023 16:29:56] "GET /admin/ HTTP/1.1" 200 7157
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:28:58
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:31:26
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:31:39
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:32:47
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 16:36:07] "GET / HTTP/1.1" 200 7899
[08/May/2023 16:36:09] "GET /pybo/200/ HTTP/1.1" 200 2762
[08/May/2023 16:36:12] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 16:36:13] "GET / HTTP/1.1" 200 7957
[08/May/2023 16:36:16] "GET /pybo/question/creat/ HTTP/1.1" 302 0
[08/May/2023 16:36:16] "GET /common/login/?next=/pybo/question/creat/ HTTP/1.1" 200 2347
[08/May/2023 16:36:18] "GET /pybo/ HTTP/1.1" 200 7957
[08/May/2023 16:36:19] "GET /pybo/200/ HTTP/1.1" 200 2820
[08/May/2023 16:36:22] "POST /pybo/answer/create/200/ HTTP/1.1" 302 0
[08/May/2023 16:36:22] "GET /common/login/?next=/pybo/answer/create/200/ HTTP/1.1" 200 2347
[08/May/2023 16:36:23] "GET /pybo/ HTTP/1.1" 200 7957
[08/May/2023 16:37:47] "GET /pybo/question/creat/ HTTP/1.1" 302 0
[08/May/2023 16:37:47] "GET /common/login/?next=/pybo/question/creat/ HTTP/1.1" 200 2413
[08/May/2023 16:37:53] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 16:37:53] "GET /pybo/question/creat/ HTTP/1.1" 200 2475
[08/May/2023 16:45:55] "GET /pybo/question/creat/ HTTP/1.1" 200 2465
[08/May/2023 16:45:56] "GET /pybo/ HTTP/1.1" 200 7901
[08/May/2023 16:45:57] "GET /pybo/202/ HTTP/1.1" 200 2820
[08/May/2023 16:45:59] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 16:45:59] "GET / HTTP/1.1" 200 7957
[08/May/2023 16:46:01] "GET /pybo/202/ HTTP/1.1" 200 2884
[08/May/2023 16:46:09] "GET /common/login/ HTTP/1.1" 200 2392
[08/May/2023 16:46:17] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 16:46:19] "GET / HTTP/1.1" 200 7899
[08/May/2023 16:46:20] "GET /pybo/202/ HTTP/1.1" 200 2818
[08/May/2023 16:46:23] "GET /pybo/ HTTP/1.1" 200 7899
[08/May/2023 16:46:25] "GET /pybo/?page=6 HTTP/1.1" 200 8645
[08/May/2023 16:46:26] "GET /pybo/?page=10 HTTP/1.1" 200 8654
[08/May/2023 16:46:27] "GET /pybo/?page=15 HTTP/1.1" 200 8645
[08/May/2023 16:46:28] "GET /pybo/?page=20 HTTP/1.1" 200 7999
[08/May/2023 16:46:29] "GET /pybo/3/ HTTP/1.1" 200 2816
[08/May/2023 16:46:31] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 16:46:31] "GET / HTTP/1.1" 200 7957
[08/May/2023 16:46:33] "GET /pybo/question/creat/ HTTP/1.1" 302 0
[08/May/2023 16:46:33] "GET /common/login/?next=/pybo/question/creat/ HTTP/1.1" 200 2413
[08/May/2023 16:46:42] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 16:46:42] "GET /pybo/question/creat/ HTTP/1.1" 200 2463
[08/May/2023 16:46:51] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 16:46:52] "GET / HTTP/1.1" 200 7957
[08/May/2023 16:46:53] "GET /common/login/ HTTP/1.1" 200 2392
[08/May/2023 16:46:59] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 16:46:59] "GET / HTTP/1.1" 200 7901
[08/May/2023 16:47:00] "GET /pybo/question/creat/ HTTP/1.1" 200 2465
[08/May/2023 16:47:09] "POST /pybo/question/creat/ HTTP/1.1" 302 0
[08/May/2023 16:47:10] "GET /pybo/ HTTP/1.1" 200 7887
[08/May/2023 16:47:13] "GET /pybo/203/ HTTP/1.1" 200 2809
[08/May/2023 16:47:19] "POST /pybo/answer/create/203/ HTTP/1.1" 302 0
[08/May/2023 16:47:20] "GET /pybo/203/ HTTP/1.1" 200 3193
[08/May/2023 16:47:22] "GET /common/logout/ HTTP/1.1" 302 0
[08/May/2023 16:47:22] "GET / HTTP/1.1" 200 8030
[08/May/2023 16:47:23] "GET /pybo/203/ HTTP/1.1" 200 3257
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:35:56
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:48:58
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[08/May/2023 16:49:39] "POST /pybo/answer/create/203/ HTTP/1.1" 302 0
[08/May/2023 16:49:39] "GET /common/login/?next=/pybo/answer/create/203/ HTTP/1.1" 200 2416
[08/May/2023 16:49:45] "POST /common/login/ HTTP/1.1" 302 0
[08/May/2023 16:49:45] "GET /pybo/answer/create/203/ HTTP/1.1" 200 3191
[08/May/2023 16:52:11] "GET /pybo/ HTTP/1.1" 200 8408
[08/May/2023 16:52:49] "GET /pybo/ HTTP/1.1" 200 8408
[08/May/2023 16:52:51] "GET /pybo/?page=2 HTTP/1.1" 200 8451
[08/May/2023 16:52:52] "GET /pybo/?page=1 HTTP/1.1" 200 8408
[08/May/2023 16:54:18] "GET /pybo/203/ HTTP/1.1" 200 3276
[08/May/2023 16:55:39] "GET /pybo/203/ HTTP/1.1" 200 3350
[08/May/2023 16:55:49] "GET /pybo/203/ HTTP/1.1" 200 3361
Not Found: /favicon.ico
[08/May/2023 17:20:01] "GET /favicon.ico HTTP/1.1" 404 2445
Not Found: /favicon.ico
[08/May/2023 17:35:14] "GET /favicon.ico HTTP/1.1" 404 2445
[09/May/2023 10:44:47] "GET /static/style.css HTTP/1.1" 304 0
[09/May/2023 10:44:47] "GET /static/bootstrap.min.css HTTP/1.1" 200 163873
[09/May/2023 10:44:47] "GET /static/bootstrap.min.js HTTP/1.1" 304 0
Not Found: /favicon.ico
[09/May/2023 10:44:47] "GET /favicon.ico HTTP/1.1" 404 2445
[10/May/2023 08:36:43] "GET /static/bootstrap.min.css HTTP/1.1" 200 163873
[10/May/2023 08:36:43] "GET /static/style.css HTTP/1.1" 304 0
[10/May/2023 08:36:43] "GET /static/bootstrap.min.js HTTP/1.1" 304 0
Not Found: /favicon.ico
[10/May/2023 08:36:43] "GET /favicon.ico HTTP/1.1" 404 2445
/workspace/py_django/projects/mysite/pybo/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 08, 2023 - 16:49:09
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 10, 2023 - 10:27:29
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/config/urls.py", line 22, in <module>
    path('pybo/', include('pybo.urls')),
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/pybo/urls.py", line 14, in <module>
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
AttributeError: module 'pybo.views' has no attribute 'question_modify'
/workspace/py_django/projects/mysite/pybo/urls.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/config/urls.py", line 22, in <module>
    path('pybo/', include('pybo.urls')),
  File "/workspace/py_django/mysite/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/py_django/projects/mysite/pybo/urls.py", line 14, in <module>
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
AttributeError: module 'pybo.views' has no attribute 'question_modify'
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
/workspace/py_django/projects/mysite/pybo/views.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 10, 2023 - 10:39:26
Django version 4.0.3, using settings 'config.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
